version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount current directory for live reload
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MEM0_API_KEY=${MEM0_API_KEY}
      - FASTAPI_ENV=development
      - PYTHONUNBUFFERED=1  # Better Python logging in containers
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  # Streamlit Frontend
  app:
    build: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Mount current directory for live updates
    environment:
      - BACKEND_URL=http://backend:8000
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped