version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend 
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MEM0_API_KEY=${MEM0_API_KEY}
      - FASTAPI_ENV=production
    command: uvicorn main:app --host 0.0.0.0 --port 8000 
    restart: unless-stopped

  # Streamlit Frontend
  app:
    build:
      context: .
      dockerfile: Dockerfile.app 
    container_name: streamlit-app
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000 
    depends_on:
      - backend 
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0 
    restart: unless-stopped
